language: ruby
rvm :
    - 2.3.3
before_install:
  - gem update --system
  - gem install bundler
gemfile: gemfile
sudo: required
services:
  - docker

before_install:
  - docker build -t vovikdevop/docker-react -f Dockerfile.dev .

  script: 
    - docker run vovikdevop/docker-react npm run test -- --coverage